# the log level, one of "trace", "debug", "info", "warn", "error"
# default is "info"
[log]
level = "info"

# the address to listen on
# no default value, must be set
[listen]
addr = "127.0.0.1:10000"

# the database path
# the path have no default value, must be set
[database]
path = "target/tmpdb/"
## two optional value, and the default are shown below
compression_factor = 5
cache_capacity = 1073741824

# the garbage collection configuration
# default values are shown below
[garbage_collection]
lock = { expire_minute = 5 }
auto_delete = { max_days = 365, lazy = false }
